#!/bin/bash

USERID=$(id -u)
LOGS_FOLDER="/var/log/Shell-scriptpractice"
LOGS_FILE="/var/log/Shell-scriptpractice/$0.log"

if [ $USERID -ne 0 ]; then
    echo "Please run with sudo access" | tee -a $LOGS_FILE
    exit 1 
fi

mkdir -p $LOGS_FOLDER
##Function name ###
VALIDATE(){
if [ $1 -ne 0 ]; then
    echo "$2....failure" | tee -a $LOGS_FILE
    exit 1 
else
echo "$2...Success" | tee -a $LOGS_FILE
fi
}

for package in $@
do
    dnf list installed $package &>>$LOGS_FILE
    if [ $? -ne 0 ]; then
        echo "$package is not installed, installing now"
        dnf install $package -y &>>$LOGS_FILE
        VALIDATE $? "$package Installation" 
    else
        echo "$package already installed, skip it"
done